### ISSUE TITLE
Fix content problem on year/2020//info/registration/conference-registration.md

### ISSUE THREAD

**Issue by momomd** [ieee-vgtc/ieeevis.org#1070]
Tina won’t proceed registration. It keeps asking me to enter a full name.
It seems like it has set minimum length since it worked with a longer random name.
Could you fix this as soon as possible so I can register for the conference. 
FYI, my first name is four characters and my last name is two characters long.

**Comment by yelper** [comment]
If you're still having issues, please e-mail web@ieeevis.org and we'll get it sorted out.
