### ISSUE TITLE
Fix content problem on year/2021//governance/area-model.md

### ISSUE THREAD

**Issue by lizmarai** [ieee-vgtc/ieeevis.org#1117]
In the Area 2 example papers, the before-the-last bullet:
Insight Documentation: G. A. Marai. “Activity-Centered Domain Characterization for Problem-Driven Scientific Visualization”, IEEE Transactions on Visualization and Computer Graphics, 24(1):913-922. doi: 10.1109/TVCG.2017.2744459

should say (the author name initials are G. E., not G. A.)
Insight Documentation: G. E. Marai. “Activity-Centered Domain Characterization for Problem-Driven Scientific Visualization”, IEEE Transactions on Visualization and Computer Graphics, 24(1):913-922. doi: 10.1109/TVCG.2017.2744459

Thank you!

**Comment by yelper** [comment]
Made the change, it'll go live in several days!
