### ISSUE TITLE
Fix content problem on year/2021//info/presenter-information/fast-forward-and-video-previews.md

### ISSUE THREAD

**Issue by vijayniisc** [ieee-vgtc/ieeevis.org#1215]
Link to 'Talk Recording Guide' is incorrect. 
Should be http://ieeevis.org/year/2021/info/presenter-information/talk-recording-guide

**Comment by spetruzza** [comment]
Thank you, pushed change to staging. You can also suggest a fix directly using the link "suggest a fix" at the bottom of each page.
