### ISSUE TITLE
Pull request instruction video

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#144]
Test run here ->
https://www.dropbox.com/s/jqt3qs4x4606iu6/pull-request-tutorial.mp4?dl=0

1. Any obvious changes or additions?
2. Does it make sense to compress, upload, and host via github/aws?

**Comment by cscheid** [comment]
I think it makes a lot of sense to host this on AWS. Two options:

- host it directly in the same git repository
- host it in a different AWS bucket

The advantage of not putting big files in the same git repository is that it'll save bandwidth for people who clone the repo. The disadvantage is that it won't be tracked automatically, and will be extra admin burden to manage an additional AWS bucket that serves HTTP files. (Nothing our infra can't do)

If we go the git route, we will also probably have to turn on git's Large File Support feature. It's easy to do, but it'll be one more step for when we're onboarding people.

**Comment by codementum** [comment]
@cscheid I compressed via Handbrake and got it down to 8.8mb- not terrible.

I like the idea of throwing it in git for simplicity.
I'm not sure what the right threshold is for Large File Support, but we could hit the switch if needed.

Closing for now since we're up on http://staging.ieeevis.org/instructions

**Comment by cscheid** [comment]
8.8MB is fine.
Maybe it’s also worth considering an upload to youtube and embedding the video?
-carlos
