### ISSUE TITLE
Fix content problem on year/2022//info/exhibition/supporters-and-exhibition.md

### ISSUE THREAD

**Issue by TKnudsen** [ieee-vgtc/ieeevis.org#1460]
Dear colleagues,

I'm in the VIS OC Supporters team and I would like to refine the IEEE VIS 2022 Supporters and Exhibition page.
I got a Word document with the content. How can I hand it in? If I paste the content here, the format gets lost.
Here is the link to the file:
https://seafile.ifi.uzh.ch/f/3b49d3ca37664598b513/?dl=1

Best,
Jürgen Bernard
-- 

Jürgen Bernard
Assistant Professor of Computer Science
University of Zurich

**Comment by RKehlbeck** [comment]
Hi Jürgen!
If you want to edit the page for the IEEE VIS 2022 Supporters and Exhibition page, you can do so by visiting the corresponding .md page on Github (https://github.com/ieee-vgtc/ieeevis.org/edit/vis2022/content/info/exhibition/supporters-and-exhibition.md), where you can edit the content and create a pull request.
