### ISSUE TITLE
Fix content problem on year/2022//blog/index.md

### ISSUE THREAD

**Issue by TKnudsen** [ieee-vgtc/ieeevis.org#1465]
Dear colleagues,

I'm one of the supporters chairs.

The IEEE VIS 2022 main menu (Contribute) does not yet offer a link to the Supporters page. Last year's conference had the following text standing there:
"[Supporters](http://ieeevis.org/year/2021/info/exhibition/supporters-and-exhibition)
Your support makes this conference possible (CFP coming soon)"

I already made a change request to the github page (https://github.com/ieee-vgtc/ieeevis.org/blob/vis2022/_data/navigation.yml) but this is long time ago and I see no changes yet.

Is this due to the staging process or some bug?
Just want to make sure that everything is allright.

Thanks, best,
J. Bernard

**Comment by Zarnosch** [comment]
Hi J. Bernard,
it is part of the staging process. You can watch the staging site here: [https://staging.ieeevis.org/year/2022/info/exhibition/supporters-and-exhibition](https://staging.ieeevis.org/year/2022/info/exhibition/supporters-and-exhibition)

We are going to make the next release after the upcoming OC meeting. If its critical, that the current changes go live, we can head for a faster release.

**Comment by Zarnosch** [comment]
Should be fixed with the release on May 18th: [v2022.1.9](https://github.com/ieee-vgtc/ieeevis.org/releases/tag/v2022.1.9)
