### ISSUE TITLE
keynote and capstone pages for 2017.

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#147]
Add these.

**Comment by cscheid** [comment]
@RossMaciejewski, http://staging.ieeevis.org/year/2017/info/overview-amp-topics/capstone and http://staging.ieeevis.org/year/2017/info/overview-amp-topics/keynote are there now.

Last year there was some last-minute table-fiddling nonsense to make the layout work. You can use  https://github.com/ieee-vgtc/ieeevis.org/blob/master/year/2016/info/overview-amp-topics/capstone.md and https://github.com/ieee-vgtc/ieeevis.org/blob/master/year/2016/info/overview-amp-topics/keynote.md as references.

It's also possibly a good time to discuss cleaning up the URL a bit. For example,

http://staging.ieeevis.org/year/2017/info/overview-amp-topics/capstone could be, instead,

http://staging.ieeevis.org/year/2017/info/capstone or even

http://staging.ieeevis.org/year/2017/capstone

These are not important, but they'd look nicer.

**Comment by RossMaciejewski** [comment]
The new URL would be fine. We would have a keynote and a capstone I suppose?

**Comment by cscheid** [comment]
Fixed.
