### ISSUE TITLE
Supporter logo process

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#152]
Some process notes via the phone call:

- Monitor "received" column in financial fast facts sheet-- these are the "confirmed" ones to go up.
- Get logos from Exhibitors and Supports / Supporter Logos / report.xls spreadsheet in Gdrive
    - This is an auto-generated report from when Supporters finish the online form for "supporting".

Basically: 
```
if(supporterInReceivedColumn && supporterInLogoSheet) 
addToSupporterJson()
```
JSON file here -> https://github.com/ieee-vgtc/ieeevis.org/blob/201f19014c3e0a3ac5cef4eb7c46af97a1ff1628/js/all_sponsors.json

**Comment by codementum** [comment]
@cscheid Did you handle supporter logos this way last year?

I'm thinking if we can convince folks to create a "ready for web" spreadsheet with...
`class, href, logo_link`, we could automate the process and reduce errors.

**Comment by cscheid** [comment]
That would be a better way, @laneharrison. Last year I handled it by grabbing emails from the supporters folks and doing it manually. I’d love a better workflow.

**Comment by cscheid** [comment]
We have a process now. I'll create a separate issue to document it.
