### ISSUE TITLE
Panels CfP

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#16]
Goal: Add Panels CfP

Google Doc: https://docs.google.com/document/d/1q3dC0WtVDBOWQIS9CrY61k8ul2Od6Ozs5ObLTTF4NhM/edit

Tentative URL: http://ieeevis.org/year/2016/info/overview-amp-topics/panels

**Comment by cscheid** [comment]
Staging URL: http://staging.ieeevis.org/year/2017/info/call-participation/panels

**Comment by aendertGT** [comment]
Panels CfP is up: https://github.com/ieee-vgtc/ieeevis.org/blob/master/year/2017/info/call-participation/panels.md

**Comment by codementum** [comment]
@aendertGT what you linked to is empty. 
Try making the changes here: https://github.com/ieee-vgtc/ieeevis.org/edit/master/year/2017/info/call-participation/panels.md and click propose file change

**Comment by aendertGT** [comment]
That's the file I edited, proposed the file change, then did a pull request (#31):
https://github.com/ieee-vgtc/ieeevis.org/pull/31

is it empty because the pull request hasn't been approved?

**Comment by codementum** [comment]
Oh I see! I missed that and was just going by your link. Thanks @aendertGT we'll notify when it's in.

**Comment by cscheid** [comment]
I merged to staging. We'll close the issue when it's in the production site.

**Comment by cscheid** [comment]
Staging URL: http://staging.ieeevis.org/year/2017/info/call-participation/panels

Ready for production review

**Comment by cscheid** [comment]
In production.
