### ISSUE TITLE
week at a glance page

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#195]
via Meghan:
> @Web, how (who) will we create the program pages? I am willing. Will it be a direct copy/update from last year or will something else be created? Please let me know how you want this process to work. Also how best to send you the final program (format)? Gautam and I work from a spreadsheet but I can amend if easier for you.
> http://ieeevis.org/year/2016/info/overview-amp-topics/week-glance

I've added a placeholder page in 2017: https://github.com/ieee-vgtc/ieeevis.org/tree/master/year/2017/info/overview-amp-topics

What's the process for getting the schedule onto the webpage?

**Comment by cscheid** [comment]
There wasn't any real process last year, and I can tell you that this is the most annoying part of the whole website. Those tables are a pain in the ass to get right. If you have any ideas..
