### ISSUE TITLE
Fix content problem on /year/2017/info/committees/conference-committee.md

### ISSUE THREAD

**Issue by mhaley1979** [ieee-vgtc/ieeevis.org#200]
Suggest a fix on bottom of this page is not working. 404 error page. Thanks.

**Comment by codementum** [comment]
@cscheid It looks like our file is `conference_committee.md` (underscore) but the actual page is `conference-committee.md` with a dash.
Think we can we safely change from `_` to `-` on our end?

**Comment by cscheid** [comment]
Maybe it's the permalink entry on the yaml front matter?

**Comment by cscheid** [comment]
Yeah, that's what it is. I think we want to keep the dash (to maintain the URL). Let me attempt a fix.

**Comment by cscheid** [comment]
closed by eb3c5d5744459d0ad2a94cc43ba9b6048f854f01
