### ISSUE TITLE
Fix content problem on /year/2017/info/committees/conference-committee.md

### ISSUE THREAD

**Issue by ingridhotz** [ieee-vgtc/ieeevis.org#201]
There is a thypo in my surname onthe web page. It should be Ingrid Hotz not  Ingrid Holtz.
Thanks

**Comment by codementum** [comment]
@ingridhotz This is fixed on http://staging.ieeevis.org/year/2017/info/committees/conference-committee, and will go live most likely this Friday. Thank you!
