### ISSUE TITLE
layout bug on desktop

### ISSUE THREAD

**Issue by mcnuttandrew** [ieee-vgtc/ieeevis.org#2046]
Nothing clicked:
<img width="2048" alt="Screenshot 2024-08-06 at 4 18 12 PM" src="https://github.com/user-attachments/assets/c3377938-4269-465f-874b-0b12c483c310">

"program" clicked
<img width="2046" alt="Screenshot 2024-08-06 at 4 18 51 PM" src="https://github.com/user-attachments/assets/9280fa4d-b0e3-444f-829c-5ea046a57e22">

On firefox if that matters

**Comment by dylancashman** [comment]
Thanks @mcnuttandrew , we will figure this one out ASAP.

**Comment by mcnuttandrew** [comment]
lookin fixed! sorry for the maybe false alarm

**Comment by dylancashman** [comment]
Unfortunately I think it's an issue with partial propagation of assets, i.e. some files are behind a CDN, some aren't, some are cached, some aren't.  This pops up every now and then when we make bigger changes (this came from adding the new list of accepted papers).  Thanks for your patience and for creating an issue with screenshot, it's always appreciated!
