### ISSUE TITLE
generate poster page from spreadsheet

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#222]
via Meghan (see bold)

> 'Program' tabs--i am missing name for welcome/keynote/BP Awards combined room. I am still working on other tabs. 
> 
> Web:
**> - poster tab is done and can go online to staging.** 
> - what sessions do you needed listed in the sessions tab? all of them or only papers sessions? last year appears to only have papers sessions in this tab.
> - what pages on staging/website will this spreadsheet produce?
> 
> thank you!

**Comment by cscheid** [comment]
This is being done now.
