### ISSUE TITLE
inconsistency between program and ieeexplore

### ISSUE THREAD

**Issue by steveharoz** [ieee-vgtc/ieeevis.org#245]
There's an inconsistency between the schedule and ieeexplore.

A paper title in the schedule is "GapChart: a Gap Strategy to Visualize the Temporal Evolution of both Ranks and Scores"

The paper title in ieeexplore is [Using Gap Charts to Visualize the Temporal Evolution of Ranks and Scores](http://ieeexplore.ieee.org/document/7579406/)

cc @charlesperin

**Comment by charlesperin** [comment]
Yes, thanks, “Using…” is the correct one.
I asked if it is possible to update the program on ieeevis in the meantime.

**Comment by cscheid** [comment]
Thanks for spotting that! We're fixing it.

**Comment by cscheid** [comment]
@mhaley1979 , can you confirm the suggested fix?

**Comment by mhaley1979** [comment]
confirmed and automated program spreadsheet has been updated if you want to push the change. 

Using Gap Charts to Visualize the Temporal Evolution of Ranks and Scores

**Comment by cscheid** [comment]
Fixed as of 163b86caa03ce22366600dd41f4c99a6ff857e53. Thanks, @steveharoz and @charlesperin !
