### ISSUE TITLE
Wrong name order on test of time awards page

### ISSUE THREAD

**Issue by romsson** [ieee-vgtc/ieeevis.org#249]
Manyeyes paper currently is

> Authors: Wattenberg, M.; Viegas, F.B.; van Ham, F.; McKeon, M.; Kriss, J.

Should be (based on [the paper in IEEE](http://ieeexplore.ieee.org/document/4376131/))

> Authors Viegas, F.B.;  Wattenberg, M.; van Ham, F.; Kriss, J.; McKeon, M.

**Comment by cscheid** [comment]
@mhaley1979 , can you check this?

**Comment by mhaley1979** [comment]
where is this paper in VIS? I don't see it on http://ieeevis.org/year/2017/info/papers

**Comment by mhaley1979** [comment]
sorry, just noticed subject...test time. i will look.

**Comment by mhaley1979** [comment]
yes, author order should be changed to 

Authors: Viegas, F.B.; Wattenberg, M.; van Ham, F.; Kriss, J.; McKeon, M.

**Comment by cscheid** [comment]
Fixed as of c69a4445828e05d9614e124aed6eb12a742d62d9. Thanks, @romsson !
