### ISSUE TITLE
finish image maps for at-a-glance program

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#252]
We now have an "At-a-Glance" page thanks to @cscheid  -> http://staging.ieeevis.org/year/2017/info/week-at-a-glance
The entries are images, so we need to add coordinates that link to different pages.

The file where coordinates should go is here -> https://github.com/ieee-vgtc/ieeevis.org/blob/master/year/2017/info/make-client-side-maps.js#L3

The steps are:
1. Identify a "rectangle" in each image that should link to a particular page.
2. Figure out the top left and bottom right coordinates of the image.
3. Add those coordinates e.g. `"coords": "93,65,189,563",` and link e.g. `"href": "http://www.visualanalyticshealthcare.org/"` to the `maps` object.

This is kind of laborious, so hopefully all of us can help. (cc @mhaley1979 @bilalsal @cscheid @codementum)

To help, I made an example video of [getting coordinates in PhotoShop](
http://www.youtube.com/watch?v=Uvllh8_NyoQ)

**Comment by cscheid** [comment]
Done.
