### ISSUE TITLE
newlines wrong bottom of workshops page

### ISSUE THREAD

**Issue by tamaramunzner** [ieee-vgtc/ieeevis.org#258]
On ieeevis.org/year/2017/info/workshops.md
For the last thing, VIP, the markdown looks reasonable but the newlines aren't there to separate the three chairs. Is that easy to fix?

**Comment by codementum** [comment]
Fixed in https://github.com/ieee-vgtc/ieeevis.org/commit/f171fac9951dd74567d747959490e803708c7e44

thanks @tamaramunzner
