### ISSUE TITLE
`content-expires` YAML metadata?

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#261]
See https://github.com/ieee-vgtc/ieeevis.org/pull/254 for a use-case

**Comment by codementum** [comment]
I should've posted here.

I like the YAML idea for two reasons:
1. Folks other than us can update or add the YAML.
2. We can create warnings in our build scripts like we do for duplicate permalinks and other things.

**Comment by cscheid** [comment]
I agree - the only small issue I see is that now we're mostly using automatic builds from the EC2 server to push to staging and production, and so we don't tend to see the warnings from the makefile.

One solution is to set up reporting infrastructure where the results of the script that pushes to S3 buckets can email us things. 

I think this is a good idea in general, except for that whole "well now we have to _implement_ it" detail.

**Comment by cscheid** [comment]
closed by 953b9d0
