### ISSUE TITLE
redirect visa-letters@ieeevis.org 

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#264]
via `nicoleb`

> - can you tell me what specific alias do you need to change?  visa-letters@ieeevis.org   - this should go to veronica@ctocevents.com (it currently goes to loren@ctocevents.com)

(ps @cscheid -- this might not be the perfect place for this but since that email contained two types or requests I'm putting it here so we don't miss it.)

**Comment by cscheid** [comment]
Fixed.
