### ISSUE TITLE
Merge best posters to production.

### ISSUE THREAD

**Issue by cgarth** [ieee-vgtc/ieeevis.org#298]
Please merge ieeevis.org/year/2017/info/awards/best-poster-awards.md from master to production.

**Comment by cscheid** [comment]
@RossMaciejewski, I'm doing this. Hope you're ok with it :)

**Comment by cscheid** [comment]
Closed by 78a6fd8

**Comment by RossMaciejewski** [comment]
Sounds good to me. I finished those this morning just hadn't checked format.
