### ISSUE TITLE
update week-at-a-glance

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#323]
from Tamara's email, action items in bold:

> It would be great to **take the new correct at-a-glance PDF file and create images that can be embedded on the HTML page**, much like the old week-at-a-glance page. Having something that's visible without using a PDF reader is extremely useful, and low effort (I hope).

This is just a matter of making new images for the page, and cleaning out the old mapping code.

**Comment by cscheid** [comment]
@tamaramunzner , the bug report had already been filed by @codementum. we're on it.

**Comment by codementum** [comment]
expired
