### ISSUE TITLE
Date inconsistencies on deadlines

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#35]
@msedl noticed some of our dates are inconsistent. From his email:

> When doing that, I noticed that our Camera-ready deadline
> has changed from the 
> google docs: Saturday, August 5
> to md: Friday, August 5
> 
> I now changed it to Friday, August 4
> as I assume this was the intention,
> 
> Please note that this issue is also the case for workshops and tutorials
> http://staging.ieeevis.org/year/2017/info/call-participation/workshops
> http://staging.ieeevis.org/year/2017/info/call-participation/tutorials
> 
> In posters it has already been fixed.

**Comment by codementum** [comment]
Dates appear up-to-date

![image](https://cloud.githubusercontent.com/assets/412089/22628501/0480933e-eba3-11e6-9963-be4e5edb3ab7.png)
