### ISSUE TITLE
Doctoral Colloquium CfP

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#36]
Goal: add DC CfP to website.

We need the link to the google docs.

**Comment by mstreit** [comment]
See https://github.com/ieee-vgtc/ieeevis.org/pull/39.

Thanks.

**Comment by cscheid** [comment]
This is a good start, thanks! I made a few comments at the pull request, just so that the content matches the other pages.

**Comment by cscheid** [comment]
Doctoral Colloquium CfP is currently on staging, and, we believe, ready for review. Will tag it as such.

**Comment by cscheid** [comment]
[staging link](http://staging.ieeevis.org/year/2017/info/call-participation/doctoral_colloquium).

**Comment by mstreit** [comment]
Looks good, thank you!

**Comment by cscheid** [comment]
This has been fixed a long time ago. (Though the URL is [slightly different](http://staging.ieeevis.org/year/2017/info/call-participation/doctoral-colloquium))
