### ISSUE TITLE
VisKids CfP

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#37]
Goal - get the VisKids CfP online.

Should we use the [2016 call](https://github.com/ieee-vgtc/ieeevis.org/blob/master/year/2016/info/committees/viskids-childcare-grants.md)?

**Comment by codementum** [comment]
One of the URLs has already been decided, ours should align w/ this:

> http://ieeevis.org/year/2017/info/committees/viskids-child-care-grants
> The above link is not active and will be referenced in the supporter prospectus.

**Comment by codementum** [comment]
viskids is up
The only remaining issue is to figure out where it should be linked on the sidebar (in progress)
