### ISSUE TITLE
sidebar menu & page stub setup

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#370]
via email from @mhaley1979 

> Will you please copy over the following pages from 2017 to staging for 2018 and/or add them to the staging menu:
> - Add main menu item: Call for Participation
> - Add CFP submenu items to menu and create a copy of 2017 page for 2018, if not already copied/created:
> — Important Dates: http://staging.ieeevis.org/year/2018/info/important-dates
> — Papers: http://staging.ieeevis.org/year/2018/info/call-participation/call-for-participation
> —— VAST: http://staging.ieeevis.org/year/2018/info/call-participation/vast-paper-types
> —— InfoVis: http://staging.ieeevis.org/year/2018/info/call-participation/infovis-paper-types
> —— SciVis: http://staging.ieeevis.org/year/2018/info/call-participation/scivis-paper-types
> — Workshops: http://staging.ieeevis.org/year/2018/info/call-participation/workshops
> — DC: http://staging.ieeevis.org/year/2018/info/call-participation/doctoral-colloquium

**Comment by mhaley1979** [comment]
thanks. i will be helping the paper chairs add the content to staging today.
