### ISSUE TITLE
call-for-participation.md

### ISSUE THREAD

**Issue by mhaley1979** [ieee-vgtc/ieeevis.org#373]
hey lane, 

call-for-participation.md calls 

{% capture my_include %}{% include important_dates-2018.md %}{% endcapture %}
{{ my_include | markdownify }}

will this still operate this way for 2018? currently important_dates-2018.md does not appear to be set up. 

thanks.

**Comment by codementum** [comment]
Fixed in https://github.com/ieee-vgtc/ieeevis.org/commit/5935ce1aeb1ac2699c57a725f9ab4c0241b958ae
