### ISSUE TITLE
forwarding for commonly missed pages

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#409]
From Christian Hege:

> Furthermore, I suggest to forward
>         http://ieeevis.org/year
> and
>         http://ieeevis.org/year/2018
> to
>         http://ieeevis.org/year/2018/welcome.

These seem to be reasonable things users might type in.
Can we somehow forward them in the same way we forward http://ieeevis.org ?

**Comment by yelper** [comment]
Do we use Apache?  I could make an htaccess file that uses ModRewrite.

**Comment by cscheid** [comment]
We don’t use apache (we use the automatic HTTP serving from Amazon S3). S3 doesn’t have server-side redirection, so all redirecting needs to happen at the client side. This means creating webpages with meta redirect at the appropriate URLs.

**Comment by Zarnosch** [comment]
I have solved that in 2023 in S3 via routing rules.
