### ISSUE TITLE
Supporters and Exhibition: Right Sidebar

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#44]
The sidebar for 2016 can return now.

@cscheid is this something trivial to turn back on?

**Comment by codementum** [comment]
I am assuming there are no changes, other than emptying the supporters list.

**Comment by cscheid** [comment]
The supporters list will be empty by default. It's now filled out through a javascript+d3 hack using the URL of the webpage to guess the year. In the old website, this was using some decrepit database code I didn't understand on the old website, and so I threw it away^W^W^W fixed it. If you look at the 2016 source you'll see what it does.

**Comment by codementum** [comment]
Supporters right sidebar is up for 2017 (Thanks Carlos)
