### ISSUE TITLE
ieeevis.org vs. www.ieeevis.org

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#57]
> ieeevis.org goes to vis 2017, but www.ieeevis.org goes to vis 2016.
- via Paul Rosen

Should we change the A tag in route 53 to the same for ieeevis.org?

**Comment by cscheid** [comment]
Yeah, this is a problem. It's not even that it's pointing to vis 2016, it's pointing to the (defunct) drupal  site. I'll shift things around.

**Comment by cscheid** [comment]
Subject to the usual "CloudFront takes 15 minutes to an hour to update", this should be fixed now. An otherwise unmatched *.ieeevis.org domain will point to ieeevis.org
