### ISSUE TITLE
Fix content problem on 2012/info/call-participation/welcome.md

### ISSUE THREAD

**Issue by jalevine** [ieee-vgtc/ieeevis.org#634]
2012 page does not have the vis program pdf available.

Current link goes to here: http://visweek.org/attachments/vis12-finalprogram-final.pdf

Which is broken.  The pdf appears missing in the https://github.com/ieee-vgtc/ieeevis.org/tree/master/year/2012

But, I found a copy here: https://web.archive.org/web/20121021032301/http://visweek.org/attachments/vis12-finalprogram-final.pdf

**Comment by jalevine** [comment]
Also, 2011 program: https://web.archive.org/web/20111206205201/http://www.visweek.org/program/program-web.pdf

**Comment by cscheid** [comment]
Do note that ieeevis.org != visweek.org, and that the web folks don't
control visweek.org (yes, another long, sad story). The solution here is to
grab things from archive.org and make manual fixes, but the web folks are
currently putting out bigger fires, so Pull Requests Welcome :)

**Comment by codementum** [comment]
@steveharoz Attempted a fix (thanks!), but the URLs on the rendered page have not updated -> http://staging.ieeevis.org/year/2011/info/call-participation/welcome

Re-opening so we can investigate further.

**Comment by steveharoz** [comment]
It was linking to the absolute URL (`http://ieeevis.org...`) instead of the relative URL (`/`)

**Comment by codementum** [comment]
@jalevine @cscheid Both 2012 and 2011 programs are accessible on staging now.
Thanks @steveharoz for the PRs!
