### ISSUE TITLE
Committee page "reporting"

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#64]
Need to handle a special case on the committee pages that are built from GDocs

> FYI - I didn’t see a way to issue a pull request for this page - if I should be handling the committee page via GitHub, let me know. From what I can tell, the committee page is still updated via the spreadsheet, not GitHub. When I click ‘Suggest a fix’ it gives me a 404 error page. I could have filed a bug but that isn’t exactly what I want to do here. Let me know how you want this page handled in future.

**Comment by cscheid** [comment]
Meh, the GitHub editing process is so nice that my vote is we move everything there. (That is, amke it all manual, but easily fixable.)
