### ISSUE TITLE
Fix content problem on /year/2019/welcome.md

### ISSUE THREAD

**Issue by sobieavila** [ieee-vgtc/ieeevis.org#665]
Hi Web Chairs! Can we get the VIS Executive Committee page up for 2019? Initial content is below. Sorry if this isn't the right way to request this. Thanks!

Lisa

| James Ahrens| *Los Alamos National Laboratory<br>(VGTC Chair)*
| Lisa Avila| *Kitware<br>(VEC Chair)*
| Sheelagh Carpendale| *University of Calgary<br>(InfoVis Steering Rep.)*
| Jason Dykes | *City, University of London<br>(InfoVis Steering Rep.)*
| Brian Fisher| *Simon Fraser University<br>(VAST Steering Rep.)*
| Aditi Majumder| *University of California, Irvine<br>(VGTC Vice-Chair for Conferences)*
| Miriah Meyer	| *University of Utah<br>(VGTC Vice-Chair)*
| Silvia Miksch| *Vienna University of Technology<br>(VAST Steering Rep.)*
| Robert Morehead| *Mississippi State University<br>(VGTC Director)*
| Klaus Mueller| *Stony Brook University<br>(VGTC Director)*
| Han-Wei Shen| *The Ohio State University<br>(SciVis Steering Rep.)*
| Deborah Silver| *Rutgers University<br>(SciVis Steering Rep.)*

**Supporting Documentation**

* [IEEE VIS Executive Committee Charter](/attachments/vec_charter_150310.pdf)
* [VIS Bid Guidelines](http://ieeevis.org/governance/bids)
* [Financial and Coordination Policies for IEEE VIS](http://ieeevis.org/governance/coordination)

**Comment by codementum** [comment]
Fixed this via email
