### ISSUE TITLE
Weekly "approval" Reports

### ISSUE THREAD

**Issue by codementum** [ieee-vgtc/ieeevis.org#70]
What's the approach for tackling "a weekly report of changed files that Core can approve" in a scalable way? 

My guess:
- Diff between staging and live to get a list of files that have been updated
- Filter or otherwise package for sending out

**Comment by cscheid** [comment]
$ git diff master..production | mail -s "weekly report" general_chair@ieeevis.org vice_chair@ieeevis.org

**Comment by codementum** [comment]
GIT GENIUS

**Comment by cscheid** [comment]
oops, i missed `--name-only`. but still

**Comment by codementum** [comment]
current output of `git diff master..production --name-only` is

```
Makefile
_includes/left_sidebar-2017.html
css/all.css
year/2017/info/committees/vast-program-committee.md
year/2017/info/exhibition/supporters-and-exhibition.md
year/2017/info/important-dates.md
year/2017/info/presenter-information/fast-forward-and-video-previews.md
```

Does that look right to you? I don't see doctoral colloquium

**Comment by cscheid** [comment]
That's because I just fixed DC:

    $ git checkout production
    $ git log year/2017/info/call-participation/doctoral-colloquium.md

    commit b4cd8f00540010e35cc52d0818ca1142dfed7c00
    Author: Carlos Scheidegger <cscheid@cs.arizona.edu>
    Date:   Fri Mar 3 11:48:45 2017 -0700
    
        pushes to production for this year

**Comment by codementum** [comment]
There is also this: https://github.com/ieee-vgtc/ieeevis.org/compare/production

**Comment by cscheid** [comment]
`s/year/week` on that commit msg ofc lol

**Comment by cscheid** [comment]
That is totally what we should point Jim to.

**Comment by codementum** [comment]
Maybe we can set up a recurring email, too, so there's a thread Jim/Core can easily reply to with questions?

**Comment by cscheid** [comment]
I'd rather keep content discussions out of email because that's how we lose track of the content.

**Comment by cscheid** [comment]
We can open a weekly github issue?

**Comment by codementum** [comment]
we now have a process in place
