### ISSUE TITLE
Fix content problem on /year/2019/welcome.md

### ISSUE THREAD

**Issue by cyberpsychologist** [ieee-vgtc/ieeevis.org#766]
Hello-- We have a capstone speaker bio and abstract, we can add a link to this page to a photo and description 
![JD_HEAD_jpg](https://user-images.githubusercontent.com/7082665/63363198-09152680-c328-11e9-9964-7f43b5ba1eca.jpeg)

Visualizing Temporality and Chronologies for the Humanities
Johanna Drucker
The charts, graphs, network diagrams, and other graphics generally grouped under the rubric “information visualizations” were almost all developed to serve the empirical, statistical, or social sciences. They use explicit quantities, standard metrics, and unambiguous visual elements to create clear, concise, legible messages. The terms on which visualizations are assessed tends to value these properties—and to be premised on the idea that the best graphics are those that “show the data”—as if data had inherent form. The difficulty with this entire set of assumptions is that they do not establish foundations for visualizing complex historical events, narrative discourse, or human experience as it is expressed in documents and artifacts where “data” are not self-evident or standard. The humanities, in adopting visualizations from empirically based fields, has failed to develop methods that engage with the interpretative aspects of its own discourse. Using three case studies—one from news narratives, one from mixed historical chronologies, one from imagined crisis scenarios—this paper argues for the development of visualizations capable of showing variable timescales, comparative chronology, and partial and unfolding temporalities. The basic components of these systems are non-linear, affective, and unable to be standardized in ways that trouble empirical approaches but serve interpretative understandings of experience and its representation in cultural expressions. The questions of how such systems might be designed and where they might have useful applications will be raised to generate discussion.
 
Are is the bio note:  
Johanna Drucker is the Breslauer Professor of Bibliographical Studies in the Department of Information Studies at UCLA. She is internationally known for her work in artists’ books, the history of graphic design, typography, experimental poetry, fine art, and digital humanities. Recent titles include: Graphesis: Visual Forms of Knowledge Production (Harvard University Press, 2014),The General Theory of Social Relativity, (The Elephants, 2018), Downdrift: An Eco-fiction (Three Rooms Press, 2018), and Visualization: Modelling Interpretation (forthcoming from B42 in Paris). In 2014 she was elected to the American Academy of Arts and Sciences and awarded an honorary doctorate of Fine Arts by the Maryland Institute College of Art in 2017.

**Comment by codementum** [comment]
Thanks! We now have this on staging ->
![image](https://user-images.githubusercontent.com/412089/63381070-f02b6600-c365-11e9-8a86-fb803baebc10.png)
