### ISSUE TITLE
Fix content problem on /year/2019/info/papers-sessions.md

### ISSUE THREAD

**Issue by SundongCandy** [ieee-vgtc/ieeevis.org#779]
Dear VIS managers,

I'm Dong Sun, a third year PhD student from the Hong Kong University of Science and Technology. I found there is a small error in the author names of the paper 

- PlanningVis: A Visual Analytics Approach to Production Planning in Smart Factories

"Ting-Chuen Pong" (https://www.cse.ust.hk/faculty/tcpong/) is misspelled as "Ting-Cheun Pong". Could you please help me correct the error? Thanks. 

Best regards,
Dong

**Comment by yelper** [comment]
Thanks for letting us know!  We've updated the spreadsheet that populates this page.  

You can see the change on our staging site: http://staging.ieeevis.org/year/2019/info/papers-sessions

This will be live by Wednesday next week (or earlier).
