### ISSUE TITLE
Fix content problem on /year/2019/info/papers-sessions.md

### ISSUE THREAD

**Issue by ChenXin360104** [ieee-vgtc/ieeevis.org#782]
Dear VIS managers,

I'm Xin Chen, a master student from the VIS lab of Shandong University. I found there are some small mistakes in the author lists of the following papers

- ShapeWordle: Tailoring Wordles using Shape-aware Archimedean Spirals
The correct author list should be **Yunhai Wang, Xiaowei Chu, Kaiyi Zhang, Chen Bao, Xiaotong Li, Jian Zhang, Chi-Wing Fu, Christophe Hurter, Oliver Deussen, and Bongshin Lee**.
- A Recursive Subdivision Technique for Sampling Multi-class Scatterplots
The correct author list should be **Xin Chen, Tong Ge, Jian Zhang, Baoquan Chen, Chi-Wing Fu, Oliver Deussen and Yunhai Wang**.
- Improving the Robustness of Scagnostics
The correct author list should be **Yunhai Wang, Zeyu Wang, Tingting Liu, Michael Correll, Zhanglin Cheng, Oliver Deussen, Michael Sedlmair**.

Could you please help me correct these mistakes? Thanks.

Best regards,
Xin

**Comment by yelper** [comment]
I've asked the InfoVis papers chairs to confirm these changes since they seem substantial.  I'll let you know once they have confirmed it!

**Comment by yelper** [comment]
Confirmed; I'll update shortly.

**Comment by yelper** [comment]
You should see this change on our staging site: http://staging.ieeevis.org/year/2019/info/papers-sessions

The updates will be pushed to the public site by next Wednesday (or earlier)!
