### ISSUE TITLE
Fix content problem on /year/2019/info/week-at-a-glance.md

### ISSUE THREAD

**Issue by alfieabdulrahman** [ieee-vgtc/ieeevis.org#783]
Got this message when I clicked on the link for "Week at a Glance":

Error
It seems like you reached a non-existing webpage. If you think this should not have happened, please use the links below to file a bug report.

<img width="1552" alt="Screen Shot 2019-09-03 at 14 26 37" src="https://user-images.githubusercontent.com/1651996/64177238-fe45b000-ce56-11e9-845f-c92457e3b2db.png">

**Comment by yelper** [comment]
Fixed via #787.  Thanks for letting us know :)
