### ISSUE TITLE
Fix content problem on /year/2019/info/meetups.md

### ISSUE THREAD

**Issue by darlingit** [ieee-vgtc/ieeevis.org#795]
Dear all, 
Would it be possible to have a "meetup" entry in the left panel under "IEEE VIS Program".
Currently there is no way to reach the meetup page from the Conference page.

Thanks!

Rita

**Comment by yelper** [comment]
Hi Rita, we just added it via 796ad08 -- you can see it on staging: http://staging.ieeevis.org/.

This will show on the production website on Wednesday, let us know if you want it to go faster and we'll engage the core commitee :)
