### ISSUE TITLE
Fix content problem on /index.md (VAST Challenge)

### ISSUE THREAD

**Issue by whiting-vastchallenge** [ieee-vgtc/ieeevis.org#82]
Sorry to do it this way - not very good at GitHub....
Could you update the VAST Challenge empty link in the left hand panel under Associated Events with a link to http://vacommunity.org/VAST+Challenge+2017 ?  Thanks!
-Mark
mark.whiting@pnnl.gov

**Comment by codementum** [comment]
Fixed in https://github.com/ieee-vgtc/ieeevis.org/commit/96baacac6eef2d5da42e3e93121555e069786853

(Thanks Mark-- you did this correctly. Catching up after VIS/UIST deadlines.)
