### ISSUE TITLE
Fix content problem on /year/2019/info/week-at-a-glance.md

### ISSUE THREAD

**Issue by razoumov** [ieee-vgtc/ieeevis.org#821]
Please fix the problem with the listed time of the tutorial "VTK-m - A ToolKit for Scientific Visualization on Many-Core Processors”. In the full program its says 2:20-5:40PM, and when clicking on the tutorial 9:00am-12:40pm.

http://ieeevis.org/year/2019/info/week-at-a-glance
http://ieeevis.org/year/2019/info/tutorials#VTK

Which one is it?

**Comment by yelper** [comment]
I've asked the tutorials chairs and scheduling administrators for clarification.

**Comment by yelper** [comment]
The "week at a glance" page is correct; the VTK-m tutorial will happen at 2:20p on Sunday.
