### ISSUE TITLE
Fix content problem on /info/application-spotlights.md

### ISSUE THREAD

**Issue by reinago** [ieee-vgtc/ieeevis.org#872]
Hi,

could you please update the app spotlight “Visualization Software Development for Researchers and End Users - from general issues to specific challenges for medical applications” to include the full list of Organizers? Since it was merged from two proposals, the organizers of one of them are all missing:
Hank Childs (University of Oregon, USA)
Takayuki Itoh 
(Ochanomizu University, Japan)
Michael Krone 
(University of Tübingen, Germany)
Guido Reina 
(University of Stuttgart, Germany)

Thank you!
Guido Reina

**Comment by kroneml** [comment]
The additional organizers are still missing. Could you please add them? Thank you very much!

**Comment by spetruzza** [comment]
organizers added (to branch 2019), it will go through to production with the rest of the website
