### ISSUE TITLE
Fix footer globally & home page header

### ISSUE THREAD

**Issue by tamaramunzner** [ieee-vgtc/ieeevis.org#887]
In the VEC meeting where the reVISe proposal was discussed, there was an agreement that future publicity would have 'visualization and visual analytics'. So the tagline in the footer should change from "THE PREMIER FORUM FOR ADVANCES IN VISUALIZATION" to "THE PREMIER FORUM FOR ADVANCES IN VISUALIZATION AND VISUAL ANALYTICS" on all pages in the footer, and also at the top of the home page.

**Comment by yelper** [comment]
Thanks for letting us know -- I'll make this change tonight.

**Comment by yelper** [comment]
fixed; you can see this on staging now!
