### ISSUE TITLE
Fix content problem on year/2020//info/call-participation/paper-keywords.md

### ISSUE THREAD

**Issue by arpitnarechania** [ieee-vgtc/ieeevis.org#929]
### As per PCS, 
**Software Architecture, Toolkit/Library, Language** - designing/implementing novel platforms/libraries/toolkits for developing or testing.

is a separate keyword. But on this [list of keywords](http://ieeevis.org/year/2020/info/call-participation/paper-keywords#keywords), it seems to be a part of the previous "Process/Workflow Design" keyword. 

### Proof
![image](https://user-images.githubusercontent.com/2376894/79701869-7b028e80-826e-11ea-8a38-7b34e0e8d6fd.png)

**Comment by yelper** [comment]
@alexsb can you help resolve this question?

**Comment by alexsb** [comment]
Yes, that's fixed in the change I just submitted yesterday.
