### ISSUE TITLE
Fix content problem on year/2020//info/call-participation/paper-submission-guidelines.md

### ISSUE THREAD

**Issue by jwoLondon** [ieee-vgtc/ieeevis.org#958]
Link to [VGTC ethics guidelines for reviewers](http://vgtc.org/about_us/conferences/ethics-guidelines) on http://ieeevis.org/year/2020/info/call-participation/paper-submission-guidelines appears to be dead. I think it is supposed to point to http://vgtc.org/conferences/ethics-guidelines

**Comment by yelper** [comment]
Thanks!
