### ISSUE TITLE
Should VAHC be linked to in http://staging.ieeevis.org/year/2017/info/workshops ?

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#97]
@RossMaciejewski, @remcochang

**Comment by cscheid** [comment]
Similarly to Vis In the Wild. Should it be there?

**Comment by RossMaciejewski** [comment]
That's currently being debated (as of 10:17 PDT 4-14)

**Comment by cscheid** [comment]
(I'm on the call :))

**Comment by RossMaciejewski** [comment]
I figured :-D

**Comment by RossMaciejewski** [comment]
Ok, so no VAHC on this page, but VIP will have something on there and Ross will coordinate w/ Remco and Bernd to get this on there

**Comment by cscheid** [comment]
And will "Vis In Practice" be added to the Associated Events sidebar? If so, I can make the change right now.

**Comment by cscheid** [comment]
oh, nevermind. it's already there.

**Comment by RossMaciejewski** [comment]
Vis In Practice is on side bar already and linked

**Comment by codementum** [comment]
@cscheid @RossMaciejewski Good to close? Looks like links are up.

**Comment by RossMaciejewski** [comment]
Should be ok to close. Vahc just goes in assoc events, that was leftover from a long discussion.

**Comment by codementum** [comment]
Spring cleaning!!! Closed thanks Ross
