### ISSUE TITLE
affiliation info needs to be corrected

### ISSUE THREAD

**Issue by bckwon** [ieee-vgtc/ieeevis.org#991]
- [ ] My affiliation is **IBM Research**, but currently written as "Harvard" on the page below. Please fix this. Thank you!
-- URL: http://ieeevis.org/year/2020/info/committees/conference-committee
-- Image: 
![image](https://user-images.githubusercontent.com/9432417/91322819-2b891d80-e78e-11ea-9a8c-73a572718b4e.png)

**Comment by yelper** [comment]
Fixed by a5c5fb25
